# Generated by Django 4.0.4 on 2022-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_image_category_image_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ManyToManyField(to='gallery.location'),
        ),
    ]
