# Generated by Django 4.0.4 on 2022-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_remove_image_location_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_photo',
            field=models.ImageField(default='media/articles/car3', upload_to='galleries/galleries'),
        ),
    ]
